### ISSUE TITLE
Failover capability with for ...try

### ISSUE THREAD

**Issue by boneyard93501** [fluencelabs/aqua#112]
it would be useful to be able to manage failover for nodes and services with a for...try statement. inputs would be a list of deployed node-id, service-id tuples where services (for now) are not stateful. the for ... try loop would iterate through the list and break when node and service were reached.  Stylized example:
```
service Local("returnService"):
  run: string -> ()

service Greeting("service-id"):
    greeting: string, bool -> string

func greeting(name: string, greeter: bool, target_tuple: []string) -> string:
  err_msg: string
  success: bool = false
  for (node, srvc) <- target_tuple:
    try:
      on node:
        Greeting srvc
        res <- Greeting.greeting(name, greeter)
        Local.run(res)
        success = true
    catch:
        err_msg <- res
    
  if success:
      <- res
  <- err_msg
  ```

**Comment by alari** [comment]
The snippet looks awesome! But it's much more than a single feature.

I suppose the best way to go now is just to augment the `for` expression syntax.

Now we have:

```python

-- common one
for a <- listOfA:
   -- this `fn` is executed for each `a`, sequentially
   -- in case of error, cycle breaks
   fn(a)

for a <- listOfA par:
   -- this `fn` is executed for all `a` in parallel
   -- error on one value does not affect the others
   fn(a)

```

Proposition for `for ... try: ` syntax:

```ruby

for a <- listOfA try:
  -- this `fn` is tried for each `a` in the list, sequentially,
  -- until there's one `fn` that does not fail
  fn(a)

```

`try...catch` language feature is covered in #28.

Ability to return one value from different branches can be done with #108.

We have no issue with the reconstruction of an object. It can be considered a sugar over the following:

```python

for tup <- target_tuple:
   node = tup.node
   srvc = tup.srvc
   ...

```

Will add it as a ticket.
