### ISSUE TITLE
CLI: --version & --help should override other options

### ISSUE THREAD

**Issue by folex** [fluencelabs/aqua#118]
Currently, if I do
```bash
aqua-cli --version
```

or 
```bash
aqua-cli --help
```

I get the following output:
```
java -jar /Users/folex/.nvm/versions/node/v14.15.2/lib/node_modules/@fluencelabs/aqua-cli/aqua-cli.jar -m node_modules --version
Unexpected option: --version

Usage: aqua-c --input <path> [--import <path>]... --output <path> [--air] [--no-relay] [--no-xor]

Aquamarine compiler

Options and flags:
...
```

The problem here is `Unexpected option: --version` (or `--help`, accordingly)

Since we have `-m node_modules`, `--version` is considered invalid. This is **unusual** for CLI tools. Usually in CLI tools (eg. gcc, cargo, etc) commands like `--version` & `--help` override all other input.

**Comment by alari** [comment]
Unfortunately, `decline` does not add these options to the set of options. Instead, it concatenates it with `orElse`, and goes from left to right. So it takes the first option (`-m`), tries to parse it as version, fails, and then switches to app options. The next one is parsed with app options, `version` is ignored. Help is parsed iff all the previous options failed, or rendered in case of error.

I suppose `help` option is of less pain. I can add `version` to the app set of flags, and figure out how to improve.
