### ISSUE TITLE
CLI: --input supports only directories (+ confusing error message)

### ISSUE THREAD

**Issue by folex** [fluencelabs/aqua#119]
So, imagine I have a file `foo.aqua` and I want to compile it. Naturally, I do
```bash
aqua-cli -i foo.aqua -o .
```
_(even more naturally I'd first go without `-i` and `-o`, just `aqua-cli foo.aqua`, so maybe we should consider allowing omitting `-i` and `-o`)_

And I see the following output:
```
java -jar /Users/folex/.nvm/versions/node/v14.15.2/lib/node_modules/@fluencelabs/aqua-cli/aqua-cli.jar -m node_modules -i foo.aqua -o .

File system error: Predicate does not hold for foo.aqua
```
It's pretty confusing: I don't get much info from that. What I see could be improved:
- State that files aren't supported as inputs, only directories are supported (or implement support for files)
- Provide more info on what predicate didn't hold. Is it "doesn't exist" or "isn't a directory" or "too long" or "invalid syntax"?

**Comment by DieMyst** [comment]
import, input and output validation as existed directories added

**Comment by DieMyst** [comment]
part with single file compilation moved to #128
