### ISSUE TITLE
Errors accumulate incorrectly

### ISSUE THREAD

**Issue by DieMyst** [fluencelabs/aqua#125]
Errors accumulate and duplicate output in geometrical (or more) progression for some reason. It depends on the number of files.
Example:
`app.aqua`
```
import "chatApp.aqua"
import "service.aqua"

func createUser(nickname: string):
    on nickname:
        AppConfig.getApp()
        AppConfig.getApp()
```
`chatApp.aqua`
```
service AppConfig("affinidi/get-config"):
    getApp: -> string
    getLocalService: -> LocalService
```
`service.aqua`
```
service Service("affinidi/chat"):
    create_user(peer_id: string, relay_id: string, nickname: string) -> string
    chats_by_peer_id(peer_id: string) -> string
```
This example will print 10 error messages about that there is no `LocalService` type. If we import another random file to `app.aqua` there will be more than a hundred error messages. After some files, aqua compiler will be stopped with OOM.

**Comment by alari** [comment]
Expected to be fixed with #114
