### ISSUE TITLE
Wait for all responses from fold-par

### ISSUE THREAD

**Issue by DieMyst** [fluencelabs/aqua#166]
There is no way to wait for all par branches in `fold` is finished their execution
```
...
nodes <- Kademlia.neighborhood(k, false)
res: *string
for n <- nodes par:
      on n:
        try:
          res <- Service.getStr()
        catch err:
          res <- Op.identity(err.msg)
-- here we can wait for 6 elements in a stream
-- but we cannot wait all elements
Op2.identity(res!5)
...
```

One way to achieve it is to have a possibility to use values in element getter `res!someValue` or `res!nodes.length`

**Comment by alari** [comment]
Depends on functors support in https://github.com/fluencelabs/AquaVM

**Comment by DieMyst** [comment]
we can join on length now. fixed
