### ISSUE TITLE
Return many values from a function

### ISSUE THREAD

**Issue by DieMyst** [fluencelabs/aqua#168]
Tuples will improve the development experience
```
func returnTuple() -> (string, u64):
...
  tuple <- (n, Service.get_millis)
  -- or without brackets
  tuple <- n, Service.get_millis
  <- tuple
```

**Comment by alari** [comment]
Tuple is a product type without field names.

Depends on VDS operations support in https://github.com/fluencelabs/AquaVM

**Comment by alari** [comment]
Product types are introduced in https://github.com/fluencelabs/aqua/pull/225

However, they are not handled by parser and generator yet, so they exist but can't be used.
