### ISSUE TITLE
name scopes

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/aqua#176]
```
 This name was already defined in the scope
```

```
func removeAllServices(initial_relay:string):    
    on initial_relay:
        services <- Srv.list()
        for srv <- services par:
            Srv.remove(srv.id)

    peers <- Kademlia.neighborhood(initial_relay, false)
    for peer <- peers:
        on peer:
            services <- Srv.list()
            for srv <- services par:
                Srv.remove(srv.id
````

if there is no plan for scopes, may be add to messages "no plan for scopes"

**Comment by alari** [comment]
These blocks are sequential:
- On `initial_relay` you define `services` variable
- It's available below, everywhere
- You're trying to define `services` again inside the `for` loop
- For loop makes a new namespace and does not _export_ anything from it, but all the data defined above is available inside the for loop

See more in the docs: https://app.gitbook.com/@fluence/s/aqua-book/language/flow

**Comment by dzmitry-lahoda** [comment]
i see, so that when i get data from any part of flow, it is embed and avail for whole flow. i do not have to return it like in rust (or may be if i want to isolate i will write function)
