### ISSUE TITLE
add generic op identity

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/aqua#187]
```
service OpContact("op"):
    identity(s: Contact) -> Contact
```

So I can op anything to return from value

**Comment by alari** [comment]
Is there any use-case for `Op.identity` besides pushing a value to a stream?

**Comment by dzmitry-lahoda** [comment]
that is most often one. if structural inheritance works, than for sure it nod needed to handle our error returns uniformly.

**Comment by alari** [comment]
Can you check the structural typing plz? It was fixed a few days ago

**Comment by alari** [comment]
The issue seems obsolete as we added `<<-` operator in #209
