### ISSUE TITLE
TypeScript: generate interfaces for Aqua services

### ISSUE THREAD

**Issue by folex** [fluencelabs/aqua#197]
Aqua service definitions describe interfaces that peers must adhere to be callable. In other words, an Aqua service definition is a requirement for a peer and peers must satisfy these requirements if they want to provide a given service.

Currently, there are three ways to create Aqua service definitions:
1. Write by hand
2. Generate it from `.wasm` file via `marine aqua service.wasm`
3. Copy from the dashboard

The last two cases are the automation and were implemented in the name of convenience. 

Now let's consider ways for a peer to adhere to an Aqua service definition:
1. If Aqua was generated via `marine aqua file.wasm`, then peers hosting service created from `file.wasm` automatically satisfy the interface.
2. However, if there's no way to serve such a service, peers must implement that interface manually.

The first case is typical for services hosted on Fluence nodes, while the second one is typical for browser-based Fluence peers. One class of situations where second case is required is mimicking an API of the existing Rust service.

To make the second case easier for developers, we could generate TypeScript `interface` definitions from Aqua `service` definitions, so developers of browser peers can implement them and be guided by the TypeScript types. That way, developers would know that they need to return `Array` for `?optional` types and see immediately if they forgot to implement some function.

**Comment by alari** [comment]
Fixed in #251
