### ISSUE TITLE
Invalid stream name scoping

### ISSUE THREAD

**Issue by folex** [fluencelabs/aqua#202]
The following Aqua code provides an invalid AIR
```
service StringOp("op"):
    array(s: string) -> []string

func use_name1() -> []string:
    results <- StringOp.array("hello")
    <- results

func use_name2() -> [][]string:
    results: *[]string
    results <- use_name1()
    results <- use_name1()
    results <- use_name1()
    <- results
```

AIR validation error
```
multiple variables found for name 'results' in data","instruction":"call %init_peer_id% ("op" "array") ["hello"] results"
```

AIR produced by **Aqua Compiler 0.1.9-162**:
```clojure
(xor
 (seq
  (seq
   (seq
    (seq
     (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
     (call %init_peer_id% ("op" "array") ["hello"] results)
    )
    (call %init_peer_id% ("op" "array") ["hello"] results)
   )
   (call %init_peer_id% ("op" "array") ["hello"] results)
  )
  (xor
   (call %init_peer_id% ("callbackSrv" "response") [results])
   (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
  )
 )
 (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
)
```

**Comment by folex** [comment]
It's interesting that this Aqua generates correct names:
```
service StringOp("op"):
    array(s: string) -> []string
    identity(ss: []string) -> []string

func use_name1() -> []string:
    results <- StringOp.array("hello")
    <- results

func use_name2() -> [][]string:
    results: *[]string
    results <- use_name1()
    results <- use_name1()
    results <- use_name1()
    <- results

func use_name3() -> [][]string:
    results: *[]string
    sss <- use_name2()
    for ss <- sss:
        results <- StringOp.identity(ss)
    <- results
```

AIR
```
(xor
 (seq
  (seq
   (seq
    (seq
     (seq
      (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
      (call %init_peer_id% ("op" "array") ["hello"] results1)
     )
     (call %init_peer_id% ("op" "array") ["hello"] results2)
    )
    (call %init_peer_id% ("op" "array") ["hello"] results3)
   )
   (fold results3 ss
    (seq
     (call %init_peer_id% ("op" "identity") [ss] $results)
     (next ss)
    )
   )
  )
  (xor
   (call %init_peer_id% ("callbackSrv" "response") [$results])
   (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
  )
 )
 (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
)
```

**Comment by alari** [comment]
It seems to be a part of a larger problem with variable names scoping. Example: 

```python
service Srv("srv"):
  put_value(value: string, service_id: []string)

func put(value: string, service_id: ?string):
    Srv.put_value(value, service_id)

func create_client_util(service_id: string):
    put(service_id, nil)
```

Here we have intersection of the argument name coming into the function, and _another_ argument's name. Which leads to the wrong recursion: `value` is dropped in this case, and replaced with `nil`.

**Comment by DieMyst** [comment]
> It's interesting that this Aqua generates correct names:
> 
> ```
> service StringOp("op"):
>     array(s: string) -> []string
>     identity(ss: []string) -> []string
> 
> func use_name1() -> []string:
>     results <- StringOp.array("hello")
>     <- results
> 
> func use_name2() -> [][]string:
>     results: *[]string
>     results <- use_name1()
>     results <- use_name1()
>     results <- use_name1()
>     <- results
> 
> func use_name3() -> [][]string:
>     results: *[]string
>     sss <- use_name2()
>     for ss <- sss:
>         results <- StringOp.identity(ss)
>     <- results
> ```
> 
> AIR
> 
> ```
> (xor
>  (seq
>   (seq
>    (seq
>     (seq
>      (seq
>       (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
>       (call %init_peer_id% ("op" "array") ["hello"] results1)
>      )
>      (call %init_peer_id% ("op" "array") ["hello"] results2)
>     )
>     (call %init_peer_id% ("op" "array") ["hello"] results3)
>    )
>    (fold results3 ss
>     (seq
>      (call %init_peer_id% ("op" "identity") [ss] $results)
>      (next ss)
>     )
>    )
>   )
>   (xor
>    (call %init_peer_id% ("callbackSrv" "response") [$results])
>    (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
>   )
>  )
>  (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
> )
> ```

this names are not correct, cause we will return only `result3` from `use_name2`, not all results
