### ISSUE TITLE
Topology optimization: move from prev scope into the fold scope outside the fold

### ISSUE THREAD

**Issue by DieMyst** [fluencelabs/aqua#205]
This aqua
```
service OpH("op"):
  pr() -> []string
  pk(s: string)

func registerKeyPutValue(node_id: string) -> []string:
  nodes <- OpH.pr()
  for n <- nodes par:
    on n:
      OpH.pk(node_id)
  <- nodes
```
generates air code that will produce hops on every iteration
```
(fold nodes n
    (par
     (seq
      (call -relay- ("op" "noop") [])
      (xor
       (call n ("op" "puk") [node_id])
       (seq
        (call -relay- ("op" "noop") [])
        (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
       )
      )
     )
     (next n)
    )
   )
  )
```
But it is possible to optimize this and call `relay` before `fold`

**Comment by alari** [comment]
The output code just works, but it's not optimal. Actually, there's just one hop to `-relay-` forced by `next_peer_ids` returned by AquaVM, but with execution trace footprint in every fold iteration, which is sub-optimal.

So this is just an optimization.
