### ISSUE TITLE
wasm we so api generates broken aqua

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/aqua#208]
```
service Notification:
```

**Comment by alari** [comment]
Hi Dzmitry!

- Absolute unclear what's the problem
- Aqua code is generated from Wasm in Marine, see https://github.com/fluencelabs/marine

**Comment by dzmitry-lahoda** [comment]
yes, marine. we have split stuff into microservices and have stubs for these with no marine endpoints. aqua generated for these seems wrong, service header with not methods
