### ISSUE TITLE
Pattern to join on a portion of peers

### ISSUE THREAD

**Issue by alari** [fluencelabs/aqua#270]
Consider the following example:

```python

res: *string
for x <- peers par:
  on x:
    res <<- x

-- once res.length is >= 2/3 of peers.length:
<- "success"
     
```

This pattern is very useful for oracles and replication, but it's not trivial to express in Aqua.

We need to provide a default solution for this problem.

**Comment by alari** [comment]
Now we can use computed scalars as join indices:

```python

res: *string
for x <- peers par:
  on x:
    res <<- x

-- once res.length is >= 2/3 of peers.length:
waitFor = 5
join res[len]


<- "success"

```

It is possible to compute this value using services. 

```python
-- Works for an array of strings
len <- Op.array_length(peers)

-- But to compute two thirds, you need to have a new service
-- So this means "wait for all"
join res[len]
```

So waiting for functors to help – depends on https://github.com/fluencelabs/aquavm/issues/149

**Comment by folex** [comment]
you can't use array_length as index in join. You first need to decrement it by 1 or it will never complete.

**Comment by alari** [comment]
Fair enough. But I cannot decrement without an arithmetics service (or functors), so there's no simple way to get from "I have this list of peers" to "I join on results from a portion of them" even for a case of "portion = full list".
