### ISSUE TITLE
CLI: add command to check compilation without emitting files

### ISSUE THREAD

**Issue by folex** [fluencelabs/aqua#290]
In `aqua-dht` I don't need to emit .ts or .js files. But I want to have a command to make sure Aqua compiles.

Having a `check` command would be awesome. I'd use it as `aqua check -i .`

**Comment by alari** [comment]
Might be `aqua -i ./aqua --dry` or something like that, as it actually performs a dry run with a compiler backend of choice.

**Comment by folex** [comment]
In rust `cargo check` works way faster than `cargo build` cuz it doesn't need to emit anything, so can optimize.

That knowledge was why I asked for a separate command, just sharing it :)

**Comment by alari** [comment]
Yeah. I think now we can do `--dry` which is cheap, and optimize later :)

Now we don't have any commands for `aqua`, it works as a single command. This will change for sure, but I think it makes sense to add `--dry` earlier and then iterate on optimizations.

**Comment by folex** [comment]
**Aqua Compiler 0.3.1-228**

```
> aqua -i . --dry

aqua.js -m node_modules -i . --dry

Aqua JS: Missing expected flag --output!
```

Seems like I can't do --dry without specifying -o

And if I do specify -o, then it will be created even though it's --dry
