### ISSUE TITLE
brace free style for function calling

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/aqua#314]
given:
```haskell
func unwrap(x:Result):
...
```

now i have to type:

```
uwnrap(result)
```

but would like
```
unwrap result
```

**Comment by alari** [comment]
What if you have many arguments?

What if you want to place another function call in place of some of the arguments?

Now we have a multivalue returns, I was planning to use brace-free calls to work with language-level product types returned from the multivalue returning function.

**Comment by dzmitry-lahoda** [comment]
> What if you have many arguments?

```
unwrap result "very bad thing"
```

>What if you want to place another function call in place of some of the arguments?

does it work right now or planned? 

```
unwrap result format("is formatting planned %v?", 42") -- works
unwrap result format "is formatting planned %v?", 42" -- fails to compile because unwrap arity is 2, not 3,  and second argument not an arrow, but string (so clear error message possible).hinted message - check your braces.
```

but overall i dislike foo("nice", bar(baz(x))) stuff, better `x -> baz -> bar -> foo "nice`

>multivalue returns,

awesome (ideal for cross service data exchange, await results from both, and return), what version of aqua supports that?

**Comment by alari** [comment]
https://doc.fluence.dev/aqua-book/language/variables#return-values multi-return is already implemented.

Since 0.1.3 https://doc.fluence.dev/aqua-book/changelog#0-1-13-august-10-2021
