### ISSUE TITLE
generates ts types for aqua types for handling service callbacks in browser

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/aqua#316]
1. define some type A { b: string } in aqua
2. generate ts with service func foo(a:A)
3. call func in TS with A
4. !!! in TS add client peer callback, receiving parsed args like onFoo(a:A, tetraplet:CallParameters) 
5. so on client we can handle any callback like it is done on Rust with types

**Comment by folex** [comment]
### 4. !!! in TS add client peer callback, receiving parsed args like onFoo(a:A, tetraplet:CallParameters)

We have been working to cure this specific need! We have introduced [Automatically Generated Service Definitions]
(https://doc.fluence.dev/docs/js-sdk/3_in_depth#service-definitions) in recent version of Aqua & JS SDK. It should fit you ideally.

Here's a small example:
**Aqua**
```clojure
data Event:
  id: string

service MyService("my-service-id"):
  receive_event(event: Event) -> bool
```
**TypeScript**
```typescript
registerMyService(client, 'my-service-id', {
  receive_event: (event: { id: string }, callParams: CallParams<'event'>) => {
    console.log("received event!");
    return true;
  }
})
```

### 3. call func in TS with A
Right now you have to have a wrapper function around service function to call it from TypeScript. Here's an example:
```clojure
data Event:
  id: string

service MyService("abcdef"):
  receive_event(event: Event) -> bool

-- wrapper function
function send_event(event: Event):
  MyService.receive_event(event)
```
