### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by Jakub1010** [fluencelabs/aqua#333]
I have the following version of aqua: 0.3.2-233
When i try to execute command 'aqua' I get message about the internal error:

```
(node:6892) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'fs' imported from [...]\npm\node_modules\@fluencelabs\aqua\aqua.js
    at packageResolve (internal/modules/esm/resolve.js:594:9)
    at moduleResolve (internal/modules/esm/resolve.js:633:14)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:726:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
    at link (internal/modules/esm/module_job.js:46:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Comment by DieMyst** [comment]
How did you install aqua and what is you npm version?

**Comment by Jakub1010** [comment]
Thanks for your quick answer.
npm:` 6.14.6`
Command to install: `npm i -g @fluencelabs/aqua`

**Comment by DieMyst** [comment]
We need more info, cause everything works for the rest.
- 'fs' is the core library in npm. Can you check if it works on simple script? Like, create a file `check.js` with this content:
```
"use strict";

const fs = require('fs');

const stat = fs.existsSync(".");
console.log(stat);
```
and run with `node check.js`. If an output will be `true` than everything ok.

- what OS do you use?
- what commant did you try to run with `aqua`?

**Comment by DieMyst** [comment]
node version is outdated. Try to update to to `>=15`

**Comment by folex** [comment]
> The output is true. I use Windows I just use the 'aqua' command. It should give me any feedback.
> 
> I have tried do this on my WSL Linux subsystem and the result is the same. npm version: `8.1.0` node version: `v12.18.3` os: `Ubuntu 20.04 LTS`


I'm not sure that's what's causing the issue, but `npm 8` usually corresponds to `node 16`, see https://nodejs.org/en/download/releases/

You can also try `npm 7` + `node 15`.

For NodeJS/NPM version management it's best to use [nvm](https://github.com/nvm-sh/nvm)

**Comment by Jakub1010** [comment]
@folex Thanks :)
