### ISSUE TITLE
add ability to merge stream of streams

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/aqua#346]
I have `*string`

I do for and get `*string` on each iteration.

I want to return `*string` which will be merged from each each of sub streams.

Not sure if any array related operations from Op can help me.

**Comment by alari** [comment]
Merge or concatenate? The problem is unclear, what exactly do you want to have?

You can write to the same stream in these iterations. Also see #321

**Comment by dzmitry-lahoda** [comment]
like rivers join into one, as soon as element appears in any of 2 sources, it goes into streams with elements of both. no specific order.  that will be good.

best would be if join will have memory and dedup already seen elements to avoid doubl work done.

**Comment by alari** [comment]
Just write to one stream. You can pass it to different functions as an argument of type `*string`, if needed.

Deduplication is a different topic that will be addressed when we have collection functions in AquaVM.
