### ISSUE TITLE
CLI: separate platform-specific commands

### ISSUE THREAD

**Issue by folex** [fluencelabs/aqua#376]
Currently, we have AquaCli available for both `.jvm` and `.js` targets. As a result, we have mocks in `.jvm` that just throw `???` (unimplemented).

I suggest moving AquaCli to `.js`. That would match the reality we have: `aqua` cli is available only for JS target. 

Also that will spare us from creating meaningless mocks.

**Comment by alari** [comment]
AquaCLI for JVM works, except the `aqua run`. Why remove it?

**Comment by folex** [comment]
To avoid creating mocks that throw `???`

**Comment by folex** [comment]
Very soon we'll have more commands, right? Almost all commands from `fldist` will be ported. And they all will rely on `aqua run` mechanics, so they won't work.

**Comment by alari** [comment]
That's absolutely ok. But JVM's CLI will still produce AIR or TS artifacts.

I see no reason to reorganize the code this way. AquaJS is already what we ship to people.

The mocks we can refactor if anyone really suffers from them.
