### ISSUE TITLE
`export` keyword is misleading when we have `import` keyword

### ISSUE THREAD

**Issue by alari** [fluencelabs/aqua#391]
https://doc.fluence.dev/aqua-book/language/header

`exports` in documentation is expressed vaguely: it's unclear that it exports to the host language, it just "exports"

However, given that we use `import` expression frequently, intuition hints that `export` is what controls `import`s. But it's not true, `declares` controls what can be `import`ed. So `import`-`export` duality is broken.

We may replace `export` keyword with smth else to make this non-duality with `import` obvious and straightforward.

- `foreign`
- `public`
- `external`

?

Or any other thoughts?

**Comment by folex** [comment]
`expose`
