### ISSUE TITLE
provide pre-compile data piping to scheduled scripts

### ISSUE THREAD

**Issue by boneyard93501** [fluencelabs/aqua#399]
it would be nice to be able to pipe data to scheduled scripts. e.g.,

```
aqua -i aqua-scripts  -o scheduled-air  -f function_name_to_parameterize  --data '{"arg1":"boo", "arg2": "yah"}' --scheduled
```

**Comment by alari** [comment]
I suppose that we should make a more close integration between `aqua run` and `aqua --scheduled`: any function application with literal arguments (resolved at compile time – no structs allowed, etc) can be used as a scheduled script.

**Comment by DieMyst** [comment]
done in #440
