### ISSUE TITLE
Cannot pass `nil` as an argument in `aqua run`

### ISSUE THREAD

**Issue by DieMyst** [fluencelabs/aqua#416]
`aqua run -f "deployScheduled(someArg, nil)"` ...

Must be possible to pass `nil` to optional arguments

**Comment by alari** [comment]
Related to #435.

If the function is parsed with common Aqua parser (as a call arrow expression basically), and then all the semantics layer is applied, we will have all the syntax features like using constants in place of arguments, or using other arrow calls, expressions, etc.
