### ISSUE TITLE
No errors, no process exit with aqua run with LocalIpfs error

### ISSUE THREAD

**Issue by alari** [fluencelabs/aqua#418]
`aqua run` has no predictable behavior when an error happens, even for the local errors: it may hang, or may print something, or keep silence.

This prevents using `aqua run` in automated scenarios and makes scripts debugging much harder, which is the main purpose of `aqua run` per se.

**Comment by DieMyst** [comment]
depends on #436

**Comment by DieMyst** [comment]
fixed
