### ISSUE TITLE
aqua dist deploy improvements

### ISSUE THREAD

**Issue by boneyard93501** [fluencelabs/aqua#421]
[ModuleConf](https://github.com/fluencelabs/aqua/blob/f311afd760d180181192c2d3dada74139c118498/npm/aqua/dist.aqua#L9)
* make optionals actually optional
* add mem_pages_count
* add `cid` as an alternative to `path`

Return values:
* return blueprint id
* return cid for each uploaded wasm module

**Comment by DieMyst** [comment]
- make optionals actually optional
- return blueprint id
done in #422

**Comment by DieMyst** [comment]
mem_pages_count is deprecated, you need to use `mex_heap_size` and pass it in style like `1Kb` or `1 Mb`

why do you need to return cids for every file and pass cids instead of paths? is it for optimization? if so, we can do it without cids. If there are any other reasons will be great to hear it

**Comment by boneyard93501** [comment]
re cids: saves the repeated upload to ipfs. ideally, and when pinned, you upload only once to ipfs and then use from ipfs for additional service deployment. more sugar than anything else.

**Comment by folex** [comment]
The thing with Fluence IPFS nodes is that they're isolated, i.e. they can't discover files on other nodes. So you need two values to reuse .wasm module: `CID` and Multiaddr of the IPFS node. 

I think intention to reduce deployment time by reusing uploaded modules is a very valid one, especially if you interact with the same IPFS node a lot. I think it's so valid that we should build it into deployment flow. Ask node if it already has that .wasm module, and reuse it if it does.

The question of module discovery or module repository is also an important one, but needs some research and design. I think the simplistic "ask and upload" approach would suffice ATM. 

What do you think? @boneyard93501 @DieMyst

**Comment by boneyard93501** [comment]
```
I think intention to reduce deployment time by reusing uploaded modules is a very valid one, especially if you interact with the same IPFS node a lot. I think it's so valid that we should build it into deployment flow. Ask node if it already has that .wasm module, and reuse it if it does.
```
that'll work. in the not so distant future, and we can move this discussion, i'd love to see our nodes networked with a Fluence/Aqua pinning. 

```
The question of module discovery or module repository is also an important one, but needs some research and design. I think the simplistic "ask and upload" approach would suffice ATM.
```
yep. it's been on my list for a while with Registry ready to roll it may actually move from _to do_ to _in progress_.
