### ISSUE TITLE
Generate AIR arithmetics

### ISSUE THREAD

**Issue by alari** [fluencelabs/aqua#423]
Since Aqua 0.6.0 it is possible to generate AIR from raw values. It is already used to flatten lambda expressions in indices (for getters). However, making arithmetics the same way will definitely make sense until we have proper AIR functors https://github.com/fluencelabs/aquavm/issues/149.

At least let's support `_-1`, `_+1`.

**Comment by boneyard93501** [comment]
or we could implement a decr version of https://github.com/fluencelabs/fluence/blob/9b2474e04cdce62d571cd28c47d0dda0baa43b76/particle-builtins/src/builtins.rs#L437 as a builtin for a quick turnaround:
```rust
fn array_length_decr(&self, args: Vec<serde_json::Value>) -> Result<JValue, JError> {
        match &args[..] {
            [JValue::Array(array)] => Ok(json!(std::cmp:::max(0, arr.len() -1))),
            [_] => Err(JError::new("op array_length's argument must be an array")),
            arr => Err(JError::new(format!(
                "op array_length accepts exactly 1 argument: {} found",
                arr.len()
            ))),
        }
    }
```

**Comment by alari** [comment]
Now we can do it with [math.aqua](https://github.com/fluencelabs/aqua-lib/pull/21) (yet generated code will not work in JS)
