### ISSUE TITLE
aqua run: don't print `Your peerId: ...` unless `--show-sk` passed

### ISSUE THREAD

**Issue by folex** [fluencelabs/aqua#469]
Right now, if you execute `aqua run`, it always prints `Your peerId: ...`. That makes it real hard to use in scripts.

```
% aqua run -i . -f 'ts_getter("abc")' --addr /dns4/kras-00.fluence.dev/tcp/19990/wss/p2p/12D3KooWSD5PToNiLQwKDXsu8JSysCwUt8BVUJEqCHcDe7P5h45e
Your peerId: 12D3KooWChHfhNtQyFpbLNAKBtfe89jMDkbjVnxRZbuJNnqLtpri
```

Since we have `--show-sk` flag, I suggest to not show `Your peerId` message unless `--show-sk` was passed

**Comment by DieMyst** [comment]
fixed in #470
