### ISSUE TITLE
aqua run: generate config and read it via --config

### ISSUE THREAD

**Issue by folex** [fluencelabs/aqua#471]
Users should be able to reuse same Secret Key / PeerId easily. For managing services, querying stuff through Registry and so on. This is a must-have for good UX.

Right now, that goal is addressed by the means of `--show-config` key in `aqua run`. We suggest user to copy-paste secret key and paste to `--sk` evey time, manually. While this approach works, it is far from optimal. It's hard to explain, it's hard to automate, it's easy to make a mistake. Bad.

So, I suggest to use a file for that. And I suggest to start with a primitive solution that consists of two parts:
1. Add `aqua config generate` to print out the same info as printed in `--show-config`. Usage will be `aqua config generate > config.json`.
2. Add `--config path` key to `run`, so people can use values from that config. 

This is a primitive solution because it doesn't handle file location. File location requires a well-thought design, and will be the next step.

**Comment by boneyard93501** [comment]
yep. that's a need. my solution proposal some time back was to integrate with a kv store or even hashi vault or to embed a kv store to ~~fldist~~ ~~aqua-cli~~  aqua to handle secrets and service management. might be easier than dealing with files especially when you have a bunch of services and secrets and if you'd like some sort of (password) protection of your data.
