### ISSUE TITLE
Syntax sugar to create optional values from usual values

### ISSUE THREAD

**Issue by folex** [fluencelabs/aqua#472]
I've an idea for the syntax!

Consider a function that takes optional string
```
func foo(a: ?string)
```

And here's a syntax that came to my mind. For literals:
```
foo(?"hello")
```

Same for variables:
```
a = "hello"
foo(?a)
```

**Comment by alari** [comment]
We already have syntax to create options: `?[a]`. Just with square braces, as all the collection-creation syntaxes.
