### ISSUE TITLE
Some typos and suggestions for documentation

### ISSUE THREAD

**Issue by vysotskylev** [fluencelabs/aqua#483]
- [Example](https://doc.fluence.dev/aqua-book/language/types#type-variance) about variance and contravariance of arrow types seems incorrect, `bar(foo4)` doesn't compile.  I think it must be `foo4: u64 -> u16` instead of `foo4: u16 -> u64`.
 - [Here:](https://doc.fluence.dev/aqua-book/language/variables#arithmetic-operators) remain -> remainder ? And the syntax highlighting of the code block seems broken.
 - [Callbacks section](https://doc.fluence.dev/aqua-book/language/topology#callbacks): in the code example I would rather write something like "Executed on the peer calling foo" instead of "Executed there, where foo is called"
 - [Contract section](https://doc.fluence.dev/aqua-book/language/flow/sequential#contract) was confusing for me, especially "arms". Maybe some additional background is needed, if so, a link would be nice.
 - [co keyword](https://doc.fluence.dev/aqua-book/language/flow/parallel#co): (nitpicking) I would rather say "completes immediately" instead of "instantly"
 - [Join expression](https://doc.fluence.dev/aqua-book/language/flow/parallel#explicit-join-expression): syntax highlighting seems broken in the last code block.
 - [Getters](https://doc.fluence.dev/aqua-book/language/variables#getters): peak -> peek ?
 - [Export data from for](https://doc.fluence.dev/aqua-book/language/flow/iterative#export-data-from-for): the `return` variable name is highlighted as a keyword. Consider changing either the name or highlighter.
 - [CRDT](https://doc.fluence.dev/aqua-book/language/crdt-streams), third code block:`%init_peer_id%` seems to mean the same as `INIT_PEER_ID`, but only the latter is mentioned previously in the doc (AFAIK). Also, typo in `Wwrite`.
 - [Stream lifecycle](https://doc.fluence.dev/aqua-book/language/crdt-streams#streams-lifecycle-and-guarantees), large code block, line 27: `-- Wait for 6 responses on resp2: it's JOIN`, why not actual `join resp2!5` ? Nearby, line 29, should it read "Once we have **6** responses, merge them" ?
 - [Stream restrictions](https://doc.fluence.dev/aqua-book/language/crdt-streams#stream-restrictions): the comment highlighting seems to be broken.
 - [Module](https://doc.fluence.dev/aqua-book/language/header#module), first code block: `Module expression may be only on the very first line of the file`, but in this code block it is on the second line :)
 - [Managing Visibility...](https://doc.fluence.dev/aqua-book/language/header/control-scope-and-visibility#managing-visibility-with-module-and-declare):  "By corollary, foo cannot be imported from another files." -> "Consequently, foo cannot be imported from other files."
 - [Constants](https://doc.fluence.dev/aqua-book/language/expressions/overrideable-constants#const): [another section](https://doc.fluence.dev/aqua-book/language/variables#constants) says that constants are ALWAYS UPPER_CASE. Whom to believe? :)

**Comment by vysotskylev** [comment]
In the case the original comment doesn't show the edits:

 - [Export data from for](https://doc.fluence.dev/aqua-book/language/flow/iterative#export-data-from-for): the return variable name is highlighted as a keyword. Consider changing either the name or highlighter.
 - [CRDT](https://doc.fluence.dev/aqua-book/language/crdt-streams), third code block:%init_peer_id% seems to mean the same as INIT_PEER_ID, but only the latter is mentioned previously in the doc (AFAIK). Also, typo in Wwrite.
 - [Stream lifecycle](https://doc.fluence.dev/aqua-book/language/crdt-streams#streams-lifecycle-and-guarantees), large code block, line 27: -- Wait for 6 responses on resp2: it's JOIN, why not actual join resp2!5 ? Nearby, line 29, should it read "Once we have 6 responses, merge them" ?
  - [Stream restrictions](https://doc.fluence.dev/aqua-book/language/crdt-streams#stream-restrictions): the comment highlighting seems to be broken.
  - [Module](https://doc.fluence.dev/aqua-book/language/header#module), first code block: Module expression may be only on the very first line of the file, but in this code block it is on the second line :)
  - [Managing Visibility...](https://doc.fluence.dev/aqua-book/language/header/control-scope-and-visibility#managing-visibility-with-module-and-declare): "By corollary, foo cannot be imported from another files." -> "Consequently, foo cannot be imported from other files."
  - [Constants](https://doc.fluence.dev/aqua-book/language/expressions/overrideable-constants#const): [another section](https://doc.fluence.dev/aqua-book/language/variables#constants) says that constants are ALWAYS UPPER_CASE. Whom to believe? :)

**Comment by vysotskylev** [comment]
Due to some bug in github the recent edits are not

**Comment by DieMyst** [comment]
thanks! everything will be fixed as soon as possible

**Comment by DieMyst** [comment]
fixed
