### ISSUE TITLE
Expose relay and %init_peer_id% as variables

### ISSUE THREAD

**Issue by coder11** [fluencelabs/aqua#65]
`relay` and `%init_peer_id% are very commonly used variables in air. Both of the variables are available already (`relay` is being injected for the every generated RequestFlow) so it won't change the current contract.

As a workaround it is possible to inject these variables with a custom handler which is very tedious.

**Comment by alari** [comment]
Can you provide an example where you need to access the current `relay`'s peer id? I want to understand why it cannot be handled by calls substitution in topology transformation.

**Comment by coder11** [comment]
from the fluentpad code

```
func updateOnlineStatuses() -> bool:
	relay <- AppConfig.get_init_relay()
	init_pid <- AppConfig.get_init_peer_id()
	allUsers <- getUserList()
	for user <- allUsers par:
		on user.peer_id via user.relay_id:
			isOnline <- Peer.is_connected(user.peer_id)
		on init_pid via relay:
			FluentPad.notifyOnline(user.peer_id, isOnline)
	<- true
```

**Comment by alari** [comment]
You can reorganize this code, for example, like this (try plz):

```
func updateOnlineStatuses():
	init_pid <- AppConfig.get_init_peer_id()
	allUsers <- getUserList()
	for user <- allUsers par:
		on user.peer_id via user.relay_id:
			isOnline <- Peer.is_connected(user.peer_id)
		FluentPad.notifyOnline(user.peer_id, isOnline)
```

Or maybe like this:

```
func updateOnlineStatuses(onPeerStatus: string, bool -> ()):
	init_pid <- AppConfig.get_init_peer_id()
	allUsers <- getUserList()
	for user <- allUsers par:
		on user.peer_id via user.relay_id:
			isOnline <- Peer.is_connected(user.peer_id)
			onPeerStatus(user.peer_id, isOnline)
```

In these cases, your code will not depend on topology (whether you're behind a relay or not).

**Comment by coder11** [comment]
Wow, I didn't know it is done automatically already. Will try!
