### ISSUE TITLE
Xor error handling does not respect the relay

### ISSUE THREAD

**Issue by coder11** [fluencelabs/aqua#66]
Currently the following script is generated for xor error handling: 

```
(xor
 ;; script here
 (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error%])
)
```

However if the particle is not on the relay when the last instruction is executed the error won't get to the client.

Take a loot at the implementation in js-sdk https://github.com/fluencelabs/fluence-js/blob/f14baeb618c25bba4f2e3dba0d52d358ae67a29d/src/internal/RequestFlowBuilder.ts#L12

**Comment by DieMyst** [comment]
Can you write an example? Because I already met with this, but it was not a bug, but a route simplification that is built into the compiler.

**Comment by coder11** [comment]
I think it actually doesn't matter which instruction was the last one because the execution may break on the remote peer anywhere inside the script. In that case we ALWAYS need the hop through the relay

**Comment by alari** [comment]
I think the best solution is to modify every `OnTag`, wrapping its contents with `xor` with the exact path to `init peer`, so that we have many `xor` wrappers instead of a single one. Each wrapper may add something like a code branch label to the callback so that it's easier to find what exactly failed in case of error.

**Comment by folex** [comment]
> Each wrapper may add something like a code branch label to the callback so that it's easier to find what exactly failed in case of error.
`%last_error%` already kinda solves this, but on the AIR level obviously. Adding Aqua expression that caused the error would pretty useful.
