### ISSUE TITLE
Improve import behavior

### ISSUE THREAD

**Issue by coder11** [fluencelabs/aqua#97]
Basically imports create a graph of dependencies between source files. Currently if you have a cycle in that graph the compiler will hang and crash with out of memory.

Quick fix: display an error message if a cyclic dependency has been found

Better fix: parse import statements, put them into a graph, do a topological sort on that graph, and include files in that order.

**Comment by alari** [comment]
Cannot reproduce, @coder11 can you provide an example, please?

Cyclic dependencies are already checked. I tried to break the checker, it shows an error as expected.

**Comment by alari** [comment]
Related to #125. When an imported file contains an error, it leads to a blow.

**Comment by dzmitry-lahoda** [comment]
```
Seems like a recursion or a loop
That happened before with import cycle
```

was able to repro
